// =====================================================================
// Shared Spond sync core
//
// REVIEW REQUIRED. This module is the pure logic behind the spond-sync
// Edge Function: the sync window, the events query, the counts
// derivation and the upsert row shape. It is shared with the Deno tests
// (spond_test.ts) so the parts that can be wrong quietly stay pinned.
// See CLAUDE.md, Spond integration, for the standing policy this code
// implements.
//
// THE CHILDREN'S DATA BOUNDARY, the rule that shapes this module. Spond
// event responses identify children and their parents: member ids in
// the response arrays, names elsewhere in the payload. This app never
// holds any of that. The four counts are derived in memory as array
// lengths and everything else is discarded. buildEventRow is the only
// place a Spond event becomes a database row, and SPOND_EVENT_COLUMNS
// is the complete set of columns it may carry: no member ids, no names,
// no payload fragments. The event's recipients object, which embeds
// member names, is never read at all; subgroup scoping is delegated to
// Spond's own subGroupId filter (see eventsQuery).
//
// Read only toward Spond: authentication is the only non GET call the
// function makes, and nothing here builds a write. The endpoint paths,
// parameter names, header shape, timestamp format and login response
// shape are ported from the reference library github.com/Olen/Spond
// (spond/spond.py and spond/base.py, read at build time, 2026-06-12),
// which targets the consumer API the Spond apps use. The library is the
// reference, not a dependency.
// =====================================================================

// The API base the reference library targets (_API_BASE_URL).
export const SPOND_API_BASE = 'https://api.spond.com/core/v1/'

// The defensive sync window: events starting between WINDOW_BACK_DAYS
// before now and WINDOW_FORWARD_DAYS after, at most MAX_EVENTS_PER_GROUP
// per mapping (the library's own default cap on the events endpoint) and
// at most MAX_TOTAL_EVENTS processed per invocation across all mappings.
export const WINDOW_BACK_DAYS = 14
export const WINDOW_FORWARD_DAYS = 90
export const MAX_EVENTS_PER_GROUP = 100
export const MAX_TOTAL_EVENTS = 500

// Timeout on every Spond request.
export const SPOND_TIMEOUT_MS = 15_000

// One spond_groups mapping row, as the function reads it. spond_name is
// a team display label, never a person.
export interface SpondMapping {
  id: string
  spond_group_id: string
  spond_subgroup_id: string | null
  spond_name: string
  team_id: string
}

// The complete set of columns a synced event row may carry, mirroring
// migration 0013's spond_events (id is generated by the database). The
// boundary test asserts buildEventRow emits exactly these keys and only
// primitive values: four integer counts and event facts, never an id
// array or anything member identifying.
export const SPOND_EVENT_COLUMNS = [
  'club_id',
  'spond_event_id',
  'title',
  'starts_at',
  'ends_at',
  'location',
  'team_id',
  'accepted_count',
  'declined_count',
  'unanswered_count',
  'waiting_count',
  'cancelled',
  'synced_at',
] as const

export interface SpondEventRow {
  club_id: string
  spond_event_id: string
  title: string
  starts_at: string
  ends_at: string | null
  location: string | null
  team_id: string
  accepted_count: number
  declined_count: number
  unanswered_count: number
  waiting_count: number
  cancelled: boolean
  synced_at: string
}

function asRecord(value: unknown): Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : {}
}

function arrayLength(value: unknown): number {
  return Array.isArray(value) ? value.length : 0
}

// A timestamp from the payload, normalised to ISO so Postgres always
// accepts it; null when missing or unreadable.
function isoTimestamp(value: unknown): string | null {
  if (typeof value !== 'string' || !value) return null
  const ms = Date.parse(value)
  return Number.isFinite(ms) ? new Date(ms).toISOString() : null
}

// The Spond timestamp format the reference library sends (_DT_FORMAT,
// "%Y-%m-%dT00:00:00.000Z"): the UTC date with the time zeroed.
export function spondTimestamp(at: Date): string {
  return at.toISOString().slice(0, 10) + 'T00:00:00.000Z'
}

export interface SyncWindow {
  from: string
  to: string
}

export function syncWindow(now: Date): SyncWindow {
  const day = 86_400_000
  return {
    from: spondTimestamp(new Date(now.getTime() - WINDOW_BACK_DAYS * day)),
    to: spondTimestamp(new Date(now.getTime() + WINDOW_FORWARD_DAYS * day)),
  }
}

// The events query for one mapping, mirroring the reference library's
// get_events parameter names and construction order: max, scheduled,
// maxStartTimestamp, minStartTimestamp, groupId, then subGroupId. The
// scheduled value mirrors the library's wire format byte for byte
// (Python str(False) is "False"): scheduled events have no responses
// yet, so they are excluded exactly as the library excludes them by
// default.
//
// Subgroup matching: when the mapping names a subgroup, the query adds
// the subGroupId filter, the recipients model the library exposes
// ("Restrict to events within this subgroup", the parameter that
// resolved the library's issue 14). Scoping is therefore Spond's own,
// the same filter the Spond app's calendar uses, covering events
// addressed to the subgroup and to the whole group. The alternative,
// parsing each event's recipients object in memory, would mean handling
// member names and ids; delegating to the server keeps that payload
// region entirely unread.
export function eventsQuery(
  mapping: Pick<SpondMapping, 'spond_group_id' | 'spond_subgroup_id'>,
  window: SyncWindow,
): URLSearchParams {
  const params = new URLSearchParams()
  params.set('max', String(MAX_EVENTS_PER_GROUP))
  params.set('scheduled', 'False')
  params.set('maxStartTimestamp', window.to)
  params.set('minStartTimestamp', window.from)
  params.set('groupId', mapping.spond_group_id)
  if (mapping.spond_subgroup_id) params.set('subGroupId', mapping.spond_subgroup_id)
  return params
}

// The four counts, taken as the lengths of the response arrays and
// nothing else. A missing array counts as zero rather than failing.
// unconfirmedIds is deliberately ignored: it is not one of the four
// counts the schema stores. The member ids inside the arrays are never
// read, only counted.
export function deriveCounts(
  responses: unknown,
): Pick<SpondEventRow, 'accepted_count' | 'declined_count' | 'unanswered_count' | 'waiting_count'> {
  const r = asRecord(responses)
  return {
    accepted_count: arrayLength(r.acceptedIds),
    declined_count: arrayLength(r.declinedIds),
    unanswered_count: arrayLength(r.unansweredIds),
    waiting_count: arrayLength(r.waitinglistIds),
  }
}

// The location as one display string: the venue name then the address,
// the two fields the reference library's own ical example reads. Null
// when the event carries no readable location.
export function deriveLocation(location: unknown): string | null {
  const loc = asRecord(location)
  const parts: string[] = []
  for (const field of ['feature', 'address'] as const) {
    const value = loc[field]
    if (typeof value === 'string' && value.trim()) parts.push(value.trim())
  }
  return parts.length > 0 ? parts.join(', ') : null
}

// One Spond event reduced to the only row this app holds: the four
// counts plus title, times, location and the cancelled flag. Everything
// else in the payload is discarded here. Null when the event lacks the
// id, title or start time the table requires; the caller counts and
// reports the skip without echoing anything from the payload. Missing
// optional fields map to null and a missing cancelled flag to false,
// the same defensive read the reference library's ical example uses.
export function buildEventRow(
  clubId: string,
  teamId: string,
  event: unknown,
  syncedAt: string,
): SpondEventRow | null {
  const e = asRecord(event)
  const id = typeof e.id === 'string' ? e.id : ''
  const title = typeof e.heading === 'string' ? e.heading.trim() : ''
  const startsAt = isoTimestamp(e.startTimestamp)
  if (!id || !title || !startsAt) return null
  return {
    club_id: clubId,
    spond_event_id: id,
    title,
    starts_at: startsAt,
    ends_at: isoTimestamp(e.endTimestamp),
    location: deriveLocation(e.location),
    team_id: teamId,
    ...deriveCounts(e.responses),
    cancelled: e.cancelled === true,
    synced_at: syncedAt,
  }
}

// The bearer token from a login response, the shape the reference
// library validates: { accessToken: { token: "<JWT>" } }. Null on any
// other shape. Nothing else is read from the response: a failed login
// can carry 2FA challenge tokens and a phone number, none of which may
// be logged or surfaced.
export function extractAccessToken(loginResult: unknown): string | null {
  const token = asRecord(asRecord(loginResult).accessToken).token
  return typeof token === 'string' && token ? token : null
}

// The ids of the groups the organiser account can see, from the groups
// response. Only the ids are read; the response's member lists, with
// their names, are discarded untouched. An unexpected response shape
// yields an empty set, so every mapping then reports as not visible
// rather than the sync guessing.
export function visibleGroupIds(groups: unknown): Set<string> {
  const ids = new Set<string>()
  if (!Array.isArray(groups)) return ids
  for (const group of groups) {
    const id = asRecord(group).id
    if (typeof id === 'string' && id) ids.add(id)
  }
  return ids
}
